CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2 -Iinclude
SRCDIR = src
CIPHERS = $(SRCDIR)/ciphers

CIPHER = cipher
FCIPHER = fcipher
BRUTE = bruteforce
FREQUENCY = freq
CAESAR_CRYPTA = ccrypta
VIGENERE_CRYPTA = vcrypta
MTABLE = mtable

PRIMARY_FILES = $(wildcard $(CIPHERS)/*.cpp) $(SRCDIR)/util.cpp

CIPHER_SOURCES = $(PRIMARY_FILES) $(SRCDIR)/cipher.cpp
CIPHER_OBJECTS = $(CIPHER_SOURCES:.cpp=.o)

FCIPHER_SOURCES = $(PRIMARY_FILES) $(SRCDIR)/fcipher.cpp
FCIPHER_OBJECTS = $(FCIPHER_SOURCES:.cpp=.o)

BRUTE_SOURCES = $(PRIMARY_FILES) $(SRCDIR)/bruteforce.cpp
BRUTE_OBJECTS = $(BRUTE_SOURCES:.cpp=.o)

FREQUENCY_SOURCES = $(PRIMARY_FILES) $(SRCDIR)/freq.cpp
FREQUENCY_OBJECTS = $(FREQUENCY_SOURCES:.cpp=.o)

CAESAR_CRYPTA_SOURCES = $(PRIMARY_FILES) $(SRCDIR)/ccrypta.cpp
CAESAR_CRYPTA_OBJECTS = $(CAESAR_CRYPTA_SOURCES:.cpp=.o)

VIGENERE_CRYPTA_SOURCES = $(PRIMARY_FILES) $(SRCDIR)/vcrypta.cpp
VIGENERE_CRYPTA_OBJECTS = $(VIGENERE_CRYPTA_SOURCES:.cpp=.o)

MTABLE_SOURCES = $(SRCDIR)/mtable.cpp
MTABLE_OBJECTS = $(MTABLE_SOURCES:.cpp=.o)

all: $(CIPHER) $(FCIPHER) $(BRUTE) $(FREQUENCY) $(CAESAR_CRYPTA) $(MTABLE) $(VIGENERE_CRYPTA)

$(CIPHER): $(CIPHER_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(CIPHER) $(CIPHER_OBJECTS)

$(FCIPHER): $(FCIPHER_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(FCIPHER) $(FCIPHER_OBJECTS)

$(BRUTE): $(BRUTE_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(BRUTE) $(BRUTE_OBJECTS)

$(FREQUENCY): $(FREQUENCY_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(FREQUENCY) $(FREQUENCY_OBJECTS)

$(CAESAR_CRYPTA): $(CAESAR_CRYPTA_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(CAESAR_CRYPTA) $(CAESAR_CRYPTA_OBJECTS)

$(MTABLE): $(MTABLE_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(MTABLE) $(MTABLE_OBJECTS)

$(VIGENERE_CRYPTA): $(VIGENERE_CRYPTA_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(VIGENERE_CRYPTA) $(VIGENERE_CRYPTA_OBJECTS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(SRCDIR)/*.o $(CIPHERS)/*.o $(CIPHER) $(FCIPHER) $(BRUTE) $(FREQUENCY) $(CAESAR_CRYPTA) $(MTABLE) $(VIGENERE_CRYPTA)